global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'artist-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['artist-api:8080']

  - job_name: 'playlist-api'
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['playlist-api:8080']

  